---
title: "Extended Data Figure 2"
output: html_notebook
---

```{r}
library(Seurat)
library(pheatmap)
```

# Dendrograms of correlation matrix
```{r}
getCorrelation <- function(file_name){
  seurat <- readRDS(paste0("../data/", file_name, ".rds"))
  seurat$UniqueSample <- paste0(seurat$Sample, "_", seurat$Mix)
  mat <- matrix(0, nrow = length(VariableFeatures(seurat)), ncol = length(unique(seurat$UniqueSample)))
  for(i in 1:length(unique(seurat$UniqueSample))){
    cells <- colnames(seurat)[seurat$UniqueSample == unique(seurat$UniqueSample)[i]]
    mat[,i] <- rowMeans(as.matrix(seurat[["RNA"]]@scale.data[VariableFeatures(seurat),cells]))
    }
  colnames(mat) <- unique(seurat$UniqueSample)
  rownames(mat) <- VariableFeatures(seurat)
  
  sample_cor <- cor(mat, method="spearman")
  
  cor_heatmap <- pheatmap(sample_cor,
                        color = viridis::viridis(100),
                        cluster_cols=T,
                        cluster_rows=T,
                        border_col = "black")
  return(cor_heatmap)
}
```

```{r}
a549_tgfb1 <- getCorrelation("A549_TGFB1")
a549_egf <- getCorrelation("A549_EGF")
a549_tnf <- getCorrelation("A549_TNF")

du145_tgfb1 <- getCorrelation("DU145_TGFB1")
du145_egf <- getCorrelation("DU145_EGF")
du145_tnf <- getCorrelation("DU145_TNF")

mcf7_tgfb1 <- getCorrelation("MCF7_TGFB1")
mcf7_egf <- getCorrelation("MCF7_EGF")
mcf7_tnf <- getCorrelation("MCF7_TNF")

ovca420_tgfb1 <- getCorrelation("OVCA420_TGFB1")
ovca420_egf <- getCorrelation("OVCA420_EGF")
ovca420_tnf <- getCorrelation("OVCA420_TNF")
```

Plot dendrograms

```{r}
saveDendrogram <- function(heatmap, sample){
  dendrogram <- ggdendrogram(heatmap, rotate=T)
  ggsave(dendrogram, filename=paste0("../figure_panels/ExtendedDataFig_2/",
                                     sample, "_dendrogram.pdf"),
         width=3, height=6)
  dendrogram
}
```


```{r}
saveDendrogram(a549_tgfb1$tree_row, "A549_TGFB1")
saveDendrogram(a549_egf$tree_row, "A549_EGF")
saveDendrogram(a549_tnf$tree_row, "A549_TNF")

saveDendrogram(du145_tgfb1$tree_row, "DU145_TGFB1")
saveDendrogram(du145_egf$tree_row, "DU145_EGF")
saveDendrogram(du145_tnf$tree_row, "DU145_TNF")

saveDendrogram(mcf7_tgfb1$tree_row, "MCF7_TGFB1")
saveDendrogram(mcf7_egf$tree_row, "MCF7_EGF")
saveDendrogram(mcf7_tnf$tree_row, "MCF7_TNF")

saveDendrogram(ovca420_tgfb1$tree_row, "OVCA420_TGFB1")
saveDendrogram(ovca420_egf$tree_row, "OVCA420_EGF")
saveDendrogram(ovca420_tnf$tree_row, "OVCA420_TNF")
```

